FROM node:22.12.0-alpine

# Set the working directory
RUN mkdir -p /app
WORKDIR /app

# Copy the application code
COPY . .

# Install project dependencies
ENV PATH /app/node_modules/.bin:$PATH
RUN yarn install

# Run dev server
CMD ["yarn", "dev"]